version: '3'
volumes:
  vs-code-server-ts:
services:
  dev:
    image: dev
    build: .
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ../:/usr/src/service
      - ~/.gitconfig:/root/.gitconfig
      - vs-code-server-ts:/root/.vscode-server
    working_dir: /usr/src/service
    command: sleep infinity